# Generated by Django 4.1.2 on 2022-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0004_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
