# Generated by Django 4.1.2 on 2022-12-29 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pininterest', '0006_comment_like_alter_comment_user_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likeforcomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likeforreply', to=settings.AUTH_USER_MODEL),
        ),
    ]
