# Generated by Django 4.1.2 on 2022-12-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0009_alter_comment_like_alter_commentreply_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='saved',
            options={'ordering': ('created_date',)},
        ),
    ]
