# Generated by Django 4.1.2 on 2022-12-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0010_alter_comment_options_alter_commentreply_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='saved',
            options={'ordering': ['-created_date']},
        ),
    ]
