# Generated by Django 4.1.2 on 2023-01-09 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0012_profilepic_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default='09/01/2023'),
        ),
    ]
