# Generated by Django 4.1.2 on 2023-01-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0013_post_created_date_time_alter_post_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
