# Generated by Django 4.1.2 on 2023-01-09 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0014_remove_post_created_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date_only',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
