# Generated by Django 4.1.2 on 2023-01-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0015_post_created_date_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date_only',
        ),
    ]
