# Generated by Django 4.1.2 on 2023-01-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0019_remove_post_followers_follow_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
