# Generated by Django 4.1.2 on 2023-01-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pininterest', '0021_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
